### ISSUE TITLE
mergesort and heapsort not found when linking under Ubuntu

### ISSUE THREAD

**Issue by multivac61** [zedshaw/liblcthw#21]
When I try to compile the library under Ubuntu 17.04 I receive the following error messages:

```build/liblcthw.a(darray_algos.o): In function `DArray_heapsort': 
liblcthw/src/lcthw/darray_algos.c:12: undefined reference to `heapsort' 
build/liblcthw.a(darray_algos.o): In function `DArray_mergesort':
liblcthw/src/lcthw/darray_algos.c:18: undefined reference to `mergesort'```

These errors appear to be related to the linker not finding heapsort and mergesort in available paths. Perhaps these sorting algorithms are not available by default.

**Comment by zedshaw** [comment]
Closing issue since I merged your pull request.
